config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post "login" => "sessions#login"
  post "register" => "users#register"
  get "logout" => "sessions#logout"

  get "home" => "app#home"

  get "player_list" => "ajax#player_list"
  get "player_list_team" => "ajax#player_list_team"
  get "manager_list_team" => "ajax#manager_list_team"
  get "year_list_team" => "ajax#year_list_team"

  get "user_management" => "user_management#user_management"
  get "add_team" => "user_management#add_team"
  post "create_team" => "user_management#create_team"

  

  get "h2h_score" => "team#h2h_score"
  post "h2h_score_results" => "team#h2h_score_results"

  get "h2h_user" => "team#h2h_user"
  post "h2h_user_results" => "team#h2h_user_results"

  get "season_sim" => "app#season_sim"
  post "season_sim_results" => "app#season_sim_results"

  get "player_impact" => "player#player_impact"
  post "player_impact_results" => "player#player_impact_results"

  get "player_value" => "player#player_value"
  post "player_value_results" => "player#player_value_results"

  get "manager_evaluation" => "app#manager_evaluation"
  post "manager_evaluation_results" => "app#manager_evaluation_results"

  get "test" => "app#test"

end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  before_filter :authenticate_user

  def user_management
    conn = OCI8.new('njiang/password@oracle.cise.ufl.edu:1521/orcl')

    @teams = []

    query = %{
      SELECT Player.fname, Player.lname, UserTeam.name, SUM(StatYear.games)
      FROM UserTeam
      INNER JOIN PlayerUserTeam p1 ON 
        p1.user_email = UserTeam.user_email
        AND p1.name = UserTeam.name
      INNER JOIN Player ON Player.pid = p1.pid
      INNER JOIN StatYear ON Player.pid = StatYear.pid
      WHERE UserTeam.user_email = :1
      GROUP BY Player.fname, Player.lname, UserTeam.name
    }

    @teams = exec(query, session[:user_id]).results.group_by{|row| row[2]}
    
    conn.logoff
  end

  def add_team; end

  def create_team
    query = %{
      INSERT INTO UserTeam
      (user_email, name)
      VALUES
      (:1, :2)
    }
    exec_commit(query, session[:user_id], params[:team_name])

    params["selected_players"].uniq.each do |player|
      next if player == ""

      query = %{
        INSERT INTO PlayerUserTeam
        (user_email, name, pid)
        VALUES
        (:1, :2, :3)
      }

      exec_commit(query, session[:user_id], params[:team_name], player)
    end

    redirect_to user_management_url
  end
end

app/views/user_management/add_team.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3>Add Team</h3>
  </div>

  <div class="panel-body">
    <%= bootstrap_form_tag url: "create_team", method: "post" do |f| %>
      <%= f.text_field :player_name, label: "Player Name (autocomplete)" %>
      <%= f.text_field :team_name, label: "Team Name", required: true %>
      <%= f.select :selected_players, [], {}, { class: "selectpicker", multiple: true } %>

      <%= f.submit "Create Team" %>
    <% end %>

  </div>
</div>

app/views/user_management/user_management.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3> User Management <a href="<%= add_team_url%>" class="btn btn-primary pull-right">Add Team</a></h3>

    
  </div>

  <div class="panel-body">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <h4>My Teams</h4>

        <% if @teams.size > 0 %>
          <% @teams.each do |team| %>
            <h3 class="centered"> <%= team.first %> </h3>
            <table class="table table-bordered datatable">
              <thead>
                <tr>
                  <th>Player Name </th>
                  <th>Games Played</th>
                </tr>
              </thead>

              <tbody>
                <% team.second.each do |row| %>
                  <tr>
                    <td><%= "#{row[0]} #{row[1]}" %></td>
                    <td><%= row[3].to_i %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        <% else %>
          No teams found.
        <% end %>
      </div>
    </div>

  </div>
</div>