config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post "login" => "sessions#login"
  post "register" => "users#register"
  get "logout" => "sessions#logout"

  get "home" => "app#home"

  get "player_list" => "ajax#player_list"
  get "player_list_team" => "ajax#player_list_team"
  get "manager_list_team" => "ajax#manager_list_team"
  get "year_list_team" => "ajax#year_list_team"

  get "user_management" => "user_management#user_management"
  get "add_team" => "user_management#add_team"
  post "create_team" => "user_management#create_team"

  

  get "h2h_score" => "team#h2h_score"
  post "h2h_score_results" => "team#h2h_score_results"

  get "h2h_user" => "team#h2h_user"
  post "h2h_user_results" => "team#h2h_user_results"

  get "season_sim" => "app#season_sim"
  post "season_sim_results" => "app#season_sim_results"

  get "player_impact" => "player#player_impact"
  post "player_impact_results" => "player#player_impact_results"

  get "player_value" => "player#player_value"
  post "player_value_results" => "player#player_value_results"

  get "manager_evaluation" => "app#manager_evaluation"
  post "manager_evaluation_results" => "app#manager_evaluation_results"

  get "test" => "app#test"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baseball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= home_url %>">BaseballGuru</a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= session[:user_id] %></a></li>
        <li><a href="<%= logout_url %>">Logout</a></li>
      </ul>

    </div><!-- /.container-fluid -->
  </nav>
  
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li>
        <a href="<%= user_management_url %>">User Management</a>
      </li>
      <li>
        <a href="<%= player_impact_url %>">Player Impact Analyser</a>
      </li>
      <li>
        <a href="<%= h2h_score_url %>">H2H Score Prediction</a>
      </li>
      <li>
        <a href="<%= h2h_user_url %>">H2H User Prediction</a>
      </li>
      <li>
        <a href="<%= season_sim_url %>">Season Simulation</a>
      </li>
      <li>
        <a href="<%= player_value_url %>">Player Value Analyser</a>
      </li>
      <li>
        <a href="<%= manager_evaluation_url %>">Manager Evaluation</a>
      </li>
    </ul>
  </div>

  <div class="container-fluid" id="main-container">
    <%= yield %>
  </div>
</body>
</html>